title: fey
description: test
baseurl: ""
url: "https://fey.github.io"
remote_theme: just-the-docs/just-the-docs
plugins:
  - jekyll-remote-theme
markdown: kramdown
encoding: utf-8
sass:
  quiet_deps: true
